version: "3"
services:
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27017:${DB_PORT}"
        networks:
            - mongo
        env_file:
            - .env
        restart: always
    app:
        container_name: "idea-board-api"
        build: .
        command: npm start
        ports:
            - "4000:${APP_PORT}"
        volumes:
            - .:/usr/app
        networks:
            - mongo
        env_file:
            - .env
        restart: always

networks:
    mongo:
        driver: bridge
